// BlockNote's stylesheet loads on every BB page, not just in Pages, and a few
// of its :has() rules make the browser re-check the whole page on each
// keystroke in BB's composer, which is ProseMirror too (40-120ms per key).
// This writes src/ui/blocknote.css from @blocknote/shadcn's stylesheet without
// them. Run it after upgrading @blocknote/shadcn: `pnpm css:blocknote`.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(root, "package.json"));
let css = readFileSync(require.resolve("@blocknote/shadcn/style.css"), "utf8");

const replace = (pattern, to, why) => {
  const next = css.replace(pattern, to);
  if (next === css) throw new Error(`BlockNote's stylesheet changed: ${why} not found. Check the rule by hand.`);
  css = next;
};
// The checkbox's wrapper is a check-list item's only div.
replace(/(\.bn-block-content\[data-content-type=checkListItem\]>div):has\(>input\)/g, "$1", "the check-list checkbox rule");

/** Splits at top-level commas, leaving those inside :is() and :has() alone. */
const selectors = text => {
  const parts = [];
  let depth = 0, start = 0;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === "(") depth++;
    else if (text[i] === ")") depth--;
    else if (text[i] === "," && !depth) { parts.push(text.slice(start, i)); start = i + 1; }
  }
  return [...parts, text.slice(start)];
};
// Suggestion (track changes) nodes aren't used in Pages.
let dropped = 0;
css = css.replace(/([^{}]*)\{([^{}]*)\}/g, (rule, selector, body) => {
  if (!selector.includes(".bn-suggestion-node")) return rule;
  dropped++;
  const kept = selectors(selector).filter(part => !part.includes(".bn-suggestion-node"));
  return kept.length ? `${kept.join(",")}{${body}}` : "";
});
if (!dropped) throw new Error("BlockNote's stylesheet changed: no suggestion-node rules found. Check the :has() rules by hand.");

const header = "/* Generated by scripts/blocknote-css.mjs from @blocknote/shadcn. Don't edit. */\n";
writeFileSync(join(root, "src/ui/blocknote.css"), header + css);
console.log(`src/ui/blocknote.css: rewrote the check-list rule, dropped ${dropped} suggestion rules`);
